# Generated by Django 5.1 on 2025-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.FloatField(),
        ),
    ]
