# Generated by Django 5.1 on 2025-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_sale_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
