# Generated by Django 5.1 on 2025-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_sale_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
