# Generated by Django 5.1 on 2025-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_sale_amount_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='S', max_length=1, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price per item (Rs.)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
